[project]
authors = [
  {name = "Андрей Владимирович Головушкин", email = "ang0l@inbox.ru"},
]
dependencies = ["textual (>=7.2.0,<8.0.0)"]
description = "Проект заметок"
name = "note_app"
requires-python = ">=3.10, <4.0"
version = "0.1.0"

[build-system]
build-backend = "poetry.core.masonry.api"
requires = ["poetry-core>=2.0.0,<3.0.0"]

[dependency-groups]
dev = [
  "pytest (>=9.0.2,<10.0.0)",
]

[tool.poetry.scripts]
app = "note_app.cli:run"
